name: TPO
main: Wertzui123\TPO\Main
version: 1.0
api: 3.0.0
author: Wertzui123
load: POSTWORLD
description: Teleport without a message for ops
website: https://github.com/Wertzui123/TPO
permissions:
  tpo:
    default: op
    description: All TPO permissions
    children:
      tpo.cmd:
        default: op
        description: All TPO commands
        children:
          tpo.cmd.tpo:
            default: op
            description: Permission for /tpo